### ISSUE TITLE
Passing through className?

### ISSUE THREAD

**Issue by hew** [mbrevda/react-image#117]
Thoughts on allowing a `className` prop to be passed through?

**Comment by mbrevda** [comment]
[All props should be passed through](https://github.com/mbrevda/react-image/blob/master/src/index.js#L137) to the underlying `<img>`. Does that address your use case?

**Comment by hew** [comment]
Yep. Missed that `{..rest}`. Thanks!

**Comment by mbrevda** [comment]
No problem! Are you doing anything particularly interesting with
react-image? I'd love to hear about it!

**Comment by hew** [comment]
@mbrevda I'm using it at work for a business intelligence product. (http://klue.com)

**Comment by mbrevda** [comment]
Cool!
