### ISSUE TITLE
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by toddmedema** [mbrevda/react-image#145]
My code:
```
export function icon(name: string, theme?: string, key?: number): JSX.Element {
  const src = [`/expedition-art/icons/${name}.svg`];
  if (theme) {
    src.unshift(`/themes/${theme}/images/icon/${name}.svg`);
  }
  return <Img key={(key === null) ? name : key} className="inline_icon svg" src={src} />;
}
```

Being called:
```
<strong>{icon('d20_small')}</strong>
```

Since you like to hear about use cases, building a custom card generator for a board game :) http://betacards.expeditiongame.com/

**Comment by mbrevda** [comment]
Can you create a limited example on https://www.webpackbin.com/ or the like?

**Comment by mbrevda** [comment]
closing due to a lack of comms

**Comment by super-cache-money** [comment]
I have the same error :/

**Comment by super-cache-money** [comment]
Does this support server side rendering?

**Comment by mbrevda** [comment]
Yes, although it won't render the actual image (just the preloader)

**Comment by super-cache-money** [comment]
I was being silly - forgot to `require` the module with `.default`

**Comment by mbrevda** [comment]
Thanks for the update!
