### ISSUE TITLE
Provide onLoaded prop.

### ISSUE THREAD

**Issue by ssbarbeee** [mbrevda/react-image#183]
Do you think that you can provide onLoad prop that will be a function called upon image load complete? 
`onLoaded: PropTypes.func`

**Comment by mbrevda** [comment]
Could you elaborate a bit more about your use case?

**Comment by aouerfelli** [comment]
@ssbarbeee do you mean something like #143?

**Comment by mbrevda** [comment]
closing due to a lack of feedback

**Comment by AntonioRedondo** [comment]
@ssbarbeee means to have some prop (`onLoaded` is a good name for it) accepting a function which would be called once the image has been downloaded. This prop would be very useful to add/remove CSS classes with transitions to create a smooth fading effect (or similar effect) between the loading React element and the image downloaded.

**Comment by AntonioRedondo** [comment]
I think the answer for this ticket is in https://github.com/mbrevda/react-image/issues/143. It would be nice if this was explained on `README.md`.

**Comment by mbrevda** [comment]
It is now possible to inject a custom image loader with any desired behavior. You can pass it as a prop to the `useImage` hook or to the component, see more [here](https://github.com/mbrevda/react-image#useimage-api).
