### ISSUE TITLE
How to add a background image with the preloader?

### ISSUE THREAD

**Issue by danilvalov** [mbrevda/react-image#184]
I want to use this library. But I don't see support to use background images with preloader.
Could you give me some solution for the case?

**Comment by danilvalov** [comment]
@mbrevda 
I have a block with dynamic width and height (there is dependence on resolution). The block has a background (image) with unknown proportions.
I need to show the background image with `background-size: contain` and with a preloader.
I don't want to use JS to process the width and height of the image (CSS is faster when my page resolution can change at any time).

**Comment by mbrevda** [comment]
This component generates an `<img>` tag - not a css `background-image`. It seems the `image-set` css property should be able to help you out. See more here:  https://css-tricks.com/responsive-images-css/
