### ISSUE TITLE
Safari svg

### ISSUE THREAD

**Issue by Antamokhin** [mbrevda/react-image#191]
Svg image not showing in safari after update my macos.
`import Img from 'react-image';
import logo from './logo.svg';
<Img src={logo}/>`

UPD: Just solved by adding decode={false}

**Comment by mbrevda** [comment]
Hmm, interesting. Could you possibly post a demo? According to the spec, decode() on svg images should just return right away

**Comment by mbrevda** [comment]
closing due to a lack of feedback

**Comment by lordofthedanse** [comment]
@mbrevda I also ran into this, and the same — `decode={false}` — fixed it for me.

**Comment by mbrevda** [comment]
This is a known issue in Safari: https://bugs.webkit.org/show_bug.cgi?id=188347

**Comment by bjruberg** [comment]
I also stumbled over this and was able to fix this thanks to searching the closed issues for safari and finding this thread. Maybe you can add a hint to the Readme?

**Comment by mbrevda** [comment]
Sounds good. Can you open a PR?

**Comment by mbrevda** [comment]
It seems this issue was [fixed](https://bugs.webkit.org/show_bug.cgi?id=201243)?

**Comment by lordofthedanse** [comment]
@mbrevda this does seem to be fixed in Safari 13.1, but it did not seemed to be fixed in 13.0.5. I think adding a note to the README make sense, à la @bjruberg’s suggestion — can’t expect all people to be running the most recent version of the browser anyway.
