### ISSUE TITLE
Server rendering issue

### ISSUE THREAD

**Issue by cslinmiso** [mbrevda/react-image#204]
Hi I meet this issue while using v1.4.0, on React server rendering. It appear that `Image` doesn't exist in node, would you fix it please? 
Thanks

```
/Users/t/Documents/Repositories/project/node_modules/react-image/cjs/index.js:247
  mockImage: (0, _propTypes.instanceOf)(Image) //used for testing only
                                        ^
ReferenceError: Image is not defined
    at Object.<anonymous> (/Users/t/Documents/Repositories/project/node_modules/react-image/cjs/index.js:247:41)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/t/Documents/Repositories/project/node_modules/babel-register/lib/node.js:152:7)
```

**Comment by psycura** [comment]
Same issue!

**Comment by mbrevda** [comment]
Noted, will get to this asap

**Comment by TamilselvanThennarasu** [comment]
I reverted to back version, it's working fine.

**Comment by mbrevda** [comment]
Can you help replicating this? I tried added ssr tests in e263bf3bd8fba2c28fa5ab3b405aa139e5c28a0d but they seem to work just fine?

**Comment by cslinmiso** [comment]
@mbrevda it's working well because the default `testEnvironment` jest runs with `jsdom`. Could you please try to override `testEnvironment` in your jest config with `node`. It might replicate the issue. :)

**Comment by mbrevda** [comment]
1.4.1  is out now - please test and let me know if this issue was properly addressed
