### ISSUE TITLE
Not working in safari

### ISSUE THREAD

**Issue by anorudes** [mbrevda/react-image#214]
Safari doesn't show the placeholder it if the picture is broken. I found the same issue, but it was closed.
https://github.com/mbrevda/react-image/issues/191

**Comment by anorudes** [comment]
Example:


```js
const placeholder = "/assets/images/svg/avatar-placeholder.svg"

const AvatarComponent = ({ user }) => {
  return (
    <Image
      src={[
        user.imageUrl,
        placeholder,
      ]}
    />
  )
}

AvatarComponent.propTypes = {
  user: userShape,
}

export default AvatarComponent
```

If placeholder contains a svg image, then the img tag is not rendered.
In other cases, everything works.

**Comment by mbrevda** [comment]
Can you please create a demo on https://codesandbox.io?

**Comment by SanichKotikov** [comment]
Safari throws an error if you try to decode an SVG image.

**Comment by mbrevda** [comment]
Thanks. I'll need a working reproduction of the issue in order to work it out. Additionally, if this is the same as #191, does the solution posted there work?

**Comment by mbrevda** [comment]
Hey - feel free to add any additional information that might aid in understanding this issue. Closing until then
