### ISSUE TITLE
Loader not displayed if previous image load was successful

### ISSUE THREAD

**Issue by miestr** [mbrevda/react-image#216]
From documentation:
If an image was previously loaded successfully (since the last time this page was loaded), the loader will not be shown and the image will be rendered directly instead.

Issue:
My image URL is a captcha-generating service, so the response changes on every call and might need some time to be loaded. So if the first call was successful, then the second time I try to load a new captcha image, the react element defined in loader property is not displayed.

**Comment by mbrevda** [comment]
There is currently no way to disable the cache. Could you add a cachebuster to the end of the url. E.g. `'https://example/photo.jpg?' + Date.now()`? That would prevent the cache from being used

**Comment by miestr** [comment]
Yes, this is definitely a solution. Thank you!
