### ISSUE TITLE
Babel issue:  Can't resolve '@babel/runtime/helpers/assertThisInitialized'

### ISSUE THREAD

**Issue by sr3d** [mbrevda/react-image#230]
I ran into this issue with Rails 5 webpacker:

./node_modules/react-image/umd/index.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/assertThisInitialized' in '[...snipped...]/node_modules/react-image/umd'
 @ ./node_modules/react-image/umd/index.js 1:394-449
 @ ./app/javascript/components/orders/dashboard/order_view.js
 @ ./app/javascript/components ^\.\/.*$
 @ ./app/javascript/packs/application.js
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/application.js

**Comment by mbrevda** [comment]
You might be missing `@babel/transform-runtime`
