### ISSUE TITLE
Support for network images

### ISSUE THREAD

**Issue by sashrika** [mbrevda/react-image#231]
Is there a support for define the jwt or similar token as the header, in the Img tag? Because we are accessing image resources which are secured only for logged in users. 
Expecting a feature something similar to https://facebook.github.io/react-native/docs/images

<Image
  source={{
    uri: 'https://facebook.github.io/react/logo-og.png',
    method: 'POST',
    **headers: {
      Pragma: 'no-cache',
    },**
    body: 'Your Body goes here',
  }}
  style={{width: 400, height: 400}}
/>

**Comment by mbrevda** [comment]
Under the cover, we are using the js img() API, which doesn't support
adding headers. Perhaps you can append the token as a query parameter.
