### ISSUE TITLE
Image getting loaded 2 times

### ISSUE THREAD

**Issue by Anenth** [mbrevda/react-image#234]
The images are getting fetch 2 times,

![image 2 times](https://user-images.githubusercontent.com/1499218/58364548-cdf38a80-7ed3-11e9-8992-710ff25c656c.gif)

As you can see in the gif, the images are fetched from 2 times.
- One is getting called from here, where we create the Image object
`this.i.src = this.sourceList[this.state.currentIndex]`

- Second is from the react component `<img />`. When we say `isLoading = true` this gets rendered and fetches the image again.

https://github.com/mbrevda/react-image/blob/master/src/index.js#L133

https://codesandbox.io/embed/exciting-sinoussi-ihc17

**Comment by mbrevda** [comment]
Which browser are is this? I only see the image loading once:

<img width="509" alt="Screen Shot 2019-05-26 at 11 48 41 AM" src="https://user-images.githubusercontent.com/293004/58379463-49c10600-7fac-11e9-8fcd-cd190f47010b.png">

**Comment by Anenth** [comment]
@mbrevda Interesting, I am on chrome

**Comment by mbrevda** [comment]
I've slightly tweaked the sandbox to [run on load](https://codesandbox.io/s/focused-elgamal-if89k) and ran it in Chrome via [webpagetest](https://www.webpagetest.org/result/190528_Q6_3729fe5460e6ea7c802895065591ec3d/). Here are the results:

[<img width="621" alt="Screen Shot 2019-05-28 at 8 10 19 AM" src="https://user-images.githubusercontent.com/293004/58452488-3767d900-8120-11e9-955e-9d907bd53827.png">](https://www.webpagetest.org/result/190528_Q6_3729fe5460e6ea7c802895065591ec3d/1/details/#waterfall_view_step1)

As the image is only being loaded once, I'm not sure what else there is to do here. Closing for now, feel free to reopen with actionable info!

**Comment by Anenth** [comment]
@mbrevda Sounds good 👍

**Comment by jhodges10** [comment]
Running into the same issue w/ Chrome 78.0.3904.97

What's odd is that if you enable the browser cache in the network tab for Chrome Dev tools, the request only runs once. The behavior in Firefox is hit or miss though. If we switch to a normal <img> tag, the issue goes away - so the bug is somewhere in react-image.

Did you end up figuring this out @Anenth, or do you want to try cache thing and see if you can generate any data that's more specific?

**Comment by Anenth** [comment]
@jhodges10 I don't remember what I did, but I somehow solved it 😅

**Comment by rajakedia1** [comment]
I am also facing this issue. Any suggestion how to solve it?
