### ISSUE TITLE
Expose img element's ref

### ISSUE THREAD

**Issue by rajatbarman** [mbrevda/react-image#238]
We could use findDomNode method, but for those who don't want to do that.
The actual image's element ref is needed to read properties like 'offsetWidth', 'offsetHeight', "this.i" doesn't provide these.
https://github.com/rajatbarman/react-image/commit/b9ead46b1a016976580ae55e64a3c6565e7804ce

**Comment by mbrevda** [comment]
[Almost all props](https://github.com/mbrevda/react-image/blob/1ff25c9b57e2af767b771cbca4957927f2309be0/src/index.js#L221) passed to <Img /> will be passed to the underlying `img`
