### ISSUE TITLE
cannot load image.

### ISSUE THREAD

**Issue by heybriancheung** [mbrevda/react-image#240]
I have been using this component for some time but recently the component cannot load image. thank you.

**Comment by mbrevda** [comment]
Uh oh, I'm so sorry to hear that your having troubles! How do you think we can go about troubleshooting the issue?

**Comment by heybriancheung** [comment]
I would like to know if there is some sort of timeout feature built in the component, like after x millisecond, it gives up loading the image, or it gives up loading the image when it receives a 404 from server?

**Comment by mbrevda** [comment]
Great question! All that and more is explained here: https://github.com/mbrevda/react-image/blob/master/README.md
