### ISSUE TITLE
Have ability to pass a function into onError

### ISSUE THREAD

**Issue by kylane** [mbrevda/react-image#241]
Ahoy - thanks for this component - has come in handy!

Any chance we can still pass an onError through to the <img> component? Would still like to handle some programatic effects via a failure.

**Comment by mbrevda** [comment]
Thanks mate!

There are other ways to go about this, namely using the `unloader` component to handle errors. See [here](https://github.com/mbrevda/react-image/pull/192) for some background.

**Comment by mbrevda** [comment]
It is now possible to inject a custom image loader with any desired behavior. You can pass it as a prop to the `useImage` hook or to the component, see more [here](https://github.com/mbrevda/react-image#useimage-api).
