### ISSUE TITLE
VisibilitySensor example in docs is incorrect

### ISSUE THREAD

**Issue by BennyCarlsson** [mbrevda/react-image#242]
The code example for not rendering the image  until the image is actually visible in the viewport wont work.

The react-visibility-sensor lib does not prevent rendering it only tells you if it's in the viewport or not.

My suggestion is to either change the lib suggestion or add a state to the code example to decide whether to render or not to render the image.

**Comment by mbrevda** [comment]
A PR would be appreciated! It would also be good to point out that this lib is almost unnecessary for below-the-fold images - you can just set them to load lazily and let the browser handle that natively. For details see here: https://addyosmani.com/blog/lazy-loading/

**Comment by RRMoelker** [comment]
Just ran into this issue.

`loading="lazy" ` attribute isn't widely supported (Chrome 75 only right now). And the readme example is still wrong.

Suggest simply dropping the section in the readme.
