### ISSUE TITLE
type declaration for module 

### ISSUE THREAD

**Issue by iangoh94** [mbrevda/react-image#243]
Any plans to include typescript declaration for react-image? For supporting typescript projects.
react-image.d.ts

**Comment by mbrevda** [comment]
Sure, as soon as someone provides the types!

**Comment by schester44** [comment]
I've created this as a start, however i'm getting the error below. Still looking into what i'm doing wrong.

```
declare module 'react-image' {
  import * as React from 'react'

  interface IImgProps {
    loader?: JSX.Element
    unloader?: JSX.Element
    decode?: boolean
    crossorigin?: string
    src: string[] | string
    container: () => JSX.Element
    loaderContainer: () => JSX.Element
    unloaderContainer: () => JSX.Element
  }

  export class Img extends React.Component<IImgProps, any> {
    constructor(props: IImgProps)
    srcToArray(src: string): []
    onLoad(): void
    onError(): void
    loadImg(): void
    unloadImg(): void
    componentDidMount(): void
    componentWillUnmount(): void
    componentWillReceiveProps(nextProps: IImgProps): void
    render(): JSX.Element
  }
}
```

the error: 
`JSX element type 'Img' does not have any construct or call signatures.`

**Comment by mbrevda** [comment]
Is the constructor line necessary or can you try removing it?

**Comment by schester44** [comment]
I've tried removing it, error message persists.

**Comment by leopaini** [comment]
I've changed a few things of your code, and now at least it's working fine. I guess there are missing some properties, but it's a beginning. 

> I've tried removing it, error message persists.

Something new

`declare module "react-image" {
  import * as React from "react";

  export interface ImgProps {
    src?: string | string[];
    loader?: JSX.Element;
    unloader?: JSX.Element;
    decode?: boolean;
    crossorigin?: string;

    container?: () => JSX.Element;
    loaderContainer?: () => JSX.Element;
    unloaderContainer?: () => JSX.Element;
  }

  export default class Img extends React.Component<ImgProps> {
    constructor(props: ImgProps) {}
    srcToArray(src: string): [];
    onLoad(): void;
    onError(): void;
    loadImg(): void;
    unloadImg(): void;
    componentDidMount(): void;
    componentWillUnmount(): void;
    componentWillReceiveProps(nextProps: IImgProps): void;
    render(): JSX.Element;
  }
}`

**Comment by schester44** [comment]
@leopaini Awesome! I'll check it out

**Comment by schester44** [comment]
```
 componentWillReceiveProps(nextProps: IImgProps): void;
```

should be

```
 componentWillReceiveProps(nextProps: ImgProps): void;
```

**Comment by leopaini** [comment]
True!, I think I've lost it in the middle of the copy paste.

**Comment by mbrevda** [comment]
Cool! What happens next? (first time working with a def file)

**Comment by schester44** [comment]
@mbrevda I'm new to TS as well so this may be off but I believe you need to include a `<name>.d.ts` file in your published package (with the contents below) and add `"types": "path-to/<name>.d.ts"`.

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

This is what I ended up using in my project.. It allows for other <img> element props such as `alt`.

```
declare module 'react-image' {
  import * as React from 'react'

  export interface ImgProps {
    // For img element props such as 'alt'
    [key: string]: any

    src?: string | string[]
    loader?: JSX.Element
    unloader?: JSX.Element
    decode?: boolean
    crossorigin?: string
    container?: () => JSX.Element
    loaderContainer?: () => JSX.Element
    unloaderContainer?: () => JSX.Element
  }

  export default class Img extends React.Component<ImgProps> {
    constructor(props: ImgProps)
    srcToArray(src: string): []
    onLoad(): void
    onError(): void
    loadImg(): void
    unloadImg(): void
    componentDidMount(): void
    componentWillUnmount(): void
    componentWillReceiveProps(nextProps: ImgProps): void
    render(): JSX.Element
  }
}
```

**Comment by mbrevda** [comment]
Got it. Would you wrap this all up in a PR?

**Comment by kevin-guertin** [comment]
Hmmm... Is this supposed to be working now? I just installed 2.2.1 through npm, I see that this is still open, though I see and have the commit for the type declaration file, and I still get a "Could not find declaration file for module 'react-image' error when attempting to import.

![image](https://user-images.githubusercontent.com/50712250/70765811-e6b97580-1d29-11ea-8b58-d3bf3121ca1c.png)

**Comment by mbrevda** [comment]
v2.2.2 should be rolling out now,  which should include the typescript declarations

**Comment by iangoh94** [comment]
react-image is really helpful, thanks everyone!
