### ISSUE TITLE
Deprecated react lifecycle functions

### ISSUE THREAD

**Issue by jharris4** [mbrevda/react-image#245]
React 16.9 was just released, and this deprecates the `componentWillReceiveProps` function that is used by this package.

It would be a good idea to switch to the new static `getDerivedStateFromProps` function instead...

**Comment by mbrevda** [comment]
There is a hooks based branch which alleviates the need for traditional
lifecycle methods. Would probably need to be a major version bump due to
the hooks-only nature.

**Comment by ranneyd** [comment]
@mbrevda could we get that branch merged?

**Comment by ranneyd** [comment]
As of react 16.9, using this lib floods my console with a scary deprecation warning

**Comment by adambisek** [comment]
+1 could you please release the new version?

**Comment by mbrevda** [comment]
The branch still needs some work before it can be merged. Hopefully, we can get to that soon

**Comment by omerkhan8** [comment]
> The branch still needs some work before it can be merged. Hopefully, we can get to that soon

@mbrevda  until that branch is merged, I've created a PR which will remove this warning from console please look into it. https://github.com/mbrevda/react-image/pull/248
