### ISSUE TITLE
onError callback?

### ISSUE THREAD

**Issue by abhimanyuBlackBuck** [mbrevda/react-image#251]
Please add an `onError` callback as well. All approaches discussed in closed issues are round about. It's worse if one is not even using `class` based components

**Comment by mbrevda** [comment]
Can you please elaborate what problem your trying to solve which can't be
accomplished via the proposed methods?

**Comment by abhimanyuBlackBuck** [comment]
Having to setup an effect in the error component when all one needs is an callback.

**Comment by mbrevda** [comment]
Adding a dedicated onError handler was discussed at length in https://github.com/mbrevda/react-image/pull/192 amongst others, including the above use case.

**Comment by mbrevda** [comment]
It is now possible to inject a custom image loader with any desired behavior. You can pass it as a prop to the `useImage` hook or to the component, see more [here](https://github.com/mbrevda/react-image#useimage-api).
