### ISSUE TITLE
Fallback not showing when the image request returns 404 with response

### ISSUE THREAD

**Issue by mayconbenito** [mbrevda/react-image#254]
I was trying to render the fallback when requesting this image
 [https://i9.ytimg.com/s_p/OLAK5uy_m3GE2SxRgBgk4qOFqfN7oH3ZxoPE5IESw/sddefault.jpg?sqp=CJSpsO4Fir7X7AMGCPO-4-IF&rs=AOn4CLCSyGYAc1bdDHBVxHS42gGDDTYYXA&v=5c58df73](url) 
but since it also returns a image it doesn't work

![InXTDu](https://user-images.githubusercontent.com/28637562/70637680-622a0280-1c16-11ea-9bbb-3078c82287ae.png)

**Comment by mbrevda** [comment]
Hmm, this may be related to the underlying browser implemented JS api. Can you post a link to reproduction in https://codesandbox.io so that we can take a closer look?

**Comment by mayconbenito** [comment]
https://codesandbox.io/s/new-cloud-tjo9b

**Comment by mbrevda** [comment]
Unfortionalty, I'm not sure what our options are here. We are using the browser's native [`Image()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement) api. It would seem as if any valid image will trigger the `onLoad` event, regardless of the http status code returned. You can try pasting this in the console for a quick demo, and you'll see that irrespective of the 404 returned the browser was able to decode the image successfully and hence triggers the `onLoad` event. FWIW it would seem that this follows the [spec](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-decode) _"If the decoding process completes successfully, resolve promise with undefined."_

```js
var x = new Image()
x.src = 'https://i9.ytimg.com/s_p/OLAK5uy_m3GE2SxRgBgk4qOFqfN7oH3ZxoPE5IESw/sddefault.jpg?sqp=CJSpsO4Fir7X7AMGCPO-4-IF&rs=AOn4CLCSyGYAc1bdDHBVxHS42gGDDTYYXA&v=5c58df73'
x.decode().then(() => console.log('load after decode')).catch(() => console.log('decode error'))
```

Closing this for now but feel free to continue the discussion! If you have any ideas I'd love to hear them,
