### ISSUE TITLE
Cache not checked when `src` prop changes

### ISSUE THREAD

**Issue by roshow** [mbrevda/react-image#257]
In `UNSAFE_componentWillReceiveProps`, when `nextProps.src !== this.props.src`, it does not check to see if any of the sources are in cache before loading. One of the results is that the `loader` is shown for a brief second instead of just loading the image from cache. 

Desired behavior: if `src` prop changes, Img should check the cache before loading

**Comment by roshow** [comment]
I may take a stab at fixing this myself. If I do, would changing `UNSAFE_componentWillReceiveProps` to `componentDidUpdate` be out scope?

**Comment by mbrevda** [comment]
I don't the implications off hand and would have to take a closer look. I plan on rewriting this as a functional component anyway (in fact, there is a branch with most of the changes), so I'm not sure I'd want to touch anything at this stage...

**Comment by mbrevda** [comment]
Should be addressed by https://github.com/mbrevda/react-image/pull/268
