### ISSUE TITLE
Question: Possibility to fire an event when `n` number of images fail to load

### ISSUE THREAD

**Issue by lwhiteley** [mbrevda/react-image#259]
Is it possible to have an event that is fired when a configurable number of images has failed

for eg.

```js
<Img 
  failureThreshold={1}  // default: src.length - 1 or just 0
  onFailureThresholdReached={() => {}} 
  src={['https://...', 'https://...']} 
 />
```

**Comment by mbrevda** [comment]
I'm hesitant to make changes to the current component until everything is moved over to functional components, but we can surely discuss in the meantime. It might make sense to add an `onBeforeLoad` even, which can then be used to compose more advanced behaviors. Here an example of what that might look like:

```js
import React, {useStat} from 'react'
import Img from 'react-image'

function ImgMaxAttempts ({maxAttempts, onMaxAttempts, exitOnMaxAttempts = false, ...rest}) {
    const [attemptCount, setAttemptCount] = useState(0)
    const onBeforeLoad = () => setAttemptCount(attempts => attempts + 1)
    
    if (attemptCount > maxAttempts) {
        onMaxAttempts()
        if (exitOnMaxAttempts) return null
    }

    return <Img onBeforeLoad={onBeforeLoad} {...rest} />
}
```

I'm a bit perplexed about the use case though. Can you elaborate on what you are trying to do?

**Comment by lwhiteley** [comment]
Ok no problem.

Its a simple use case of setting an error state actually.

to be more elaborate i want to curate a list of actionable items for a user to address. One of which is a broken image link. Its an edge case  in my scenario but a possible case nonetheless and was just curious if this is on the roadmap for this plugin

**Comment by mbrevda** [comment]
Couldn't you use the `unloader` prop instead? Just pass it a component and do whatever you need to there

**Comment by lwhiteley** [comment]
Yup that makes sense, i thought about it but it seemed like a hack and less readable to me; so this entire behaviour would be hidden somewhere else deep in another component

How i thought about it in my mental model was that the `src` array's final value would be my fallback image which is always available. So once the previous images fail then an event is fired but i can still show a default image.

With the suggested approach.
My fallback image would be the unloader component and only if rendered I would fire an event to store the error. Also makes this component non-reusable.

So would end up in way more code being written when a simpler hook could have been more useful.

**Comment by mbrevda** [comment]
Would be great to get some feedback on the latest version ([PR here](https://github.com/mbrevda/react-image/pull/268)), which allows for the image loader to be injected. This should allow for this and other advanced use cases!
