### ISSUE TITLE
TS Interface Error for `src` attribute

### ISSUE THREAD

**Issue by akleiner2** [mbrevda/react-image#260]
Hi there! I just tried to upgrade this package from `1.3.1` to `2.3.0` to take advantage of the new TS declaration, but realized that I'm getting a TS error regarding the `src` attribute. Specifically the error is: 

```
Interface 'ImgProps' incorrectly extends interface 'Pick<DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>
...

 Types of property 'src' are incompatible.
    Type 'string | string[]' is not assignable to type 'string'.
      Type 'string[]' is not assignable to type 'string'.

4     export interface ImgProps extends React.ComponentPropsWithoutRef<'img'> {
                       ~~~~~~~~


Found 1 error.
```

Updating the TS definition to `export interface ImgProps extends Omit<React.ComponentPropsWithoutRef<'img'>, 'src'> { ... }` seems to fix the issue, since it looks like the underlying `src` DOM attribute is expecting a string. 

Curious about a good path forward. Are others seeing this? If so, happy to put up a PR to fix. Let me know -- thanks!

**Comment by timbastin** [comment]
Hi, I am having the same issue!

**Comment by solanoam** [comment]
Same issue:
`/usr/src/app/client/node_modules/react-image/react-image.d.ts
(4,22): error TS2430: Interface 'ImgProps' incorrectly extends interface 'Pick<DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>, "style" | "title" | ... 261 more ... | "useMap">'.
  Types of property 'src' are incompatible.
    Type 'string | string[] | undefined' is not assignable to type 'string | undefined'.
      Type 'string[]' is not assignable to type 'string'.`

**Comment by mbrevda** [comment]
paging the TS gurus: @jbelloin @schester44 @leopaini

**Comment by jbelloin** [comment]
Hi,
Agreed we should update to
`ImgProps extends Omit<React.ComponentPropsWithoutRef<'img'>, 'src'> { ... }`

**Comment by timbastin** [comment]
Do you prefer a pull request or doing it on your own?

Jerome <notifications@github.com> schrieb am Di., 11. Feb. 2020, 08:26:

**Comment by mbrevda** [comment]
PR are always helpful. If you bump the package version (minor) and update the changelog we can deploy simply by merging!

**Comment by akleiner2** [comment]
Awesome :). @mbrevda, would it be possible to get a release that includes `9ddad25`? Would love to upgrade.
