### ISSUE TITLE
Module fails on live reload

### ISSUE THREAD

**Issue by theitfactor** [mbrevda/react-image#263]
When running my react application and a code change is detected, the rebuild starts and it immediately fails with the following error:

[!] Error: Could not load react-image (imported by C:\Source\REACT-GADGETS-01\src\components\UserSnapshot\UserSnapshot.tsx): ENOENT: no such file or directory, open 'C:\Source\gadgets-modern\OGDE-REACT-GADGETS-01\react-image'

The path it is look at is the root of the project and not the node_modules folder. If I break out of the build and restart via NPM START it works fine.

The correct path is C:\Source\gadgets-modern\OGDE-REACT-GADGETS-01\node_modules\react-image

**Comment by mbrevda** [comment]
Not even sure where to begin... providing a minimal reproduction might help!

**Comment by mbrevda** [comment]
closing due to a lack of response
