### ISSUE TITLE
Force loading state by property

### ISSUE THREAD

**Issue by danzawadzki** [mbrevda/react-image#265]
I wonder if it is possible to force render of the component in the loader state by passing a flag similar to `isLoading`?

I have a component that makes a request to API first, and on the basis of the response i pass properties to the image. Because my hook to communicate with api returns isLoading flag, I would like to pass it to the image to force the loader to display before it even gets the path and name.

**Comment by mbrevda** [comment]
It sounds like you want to conditionally render just the loader based on a variable. In which case, couldn't you conditionally render the loader based on a variable?

**Comment by mbrevda** [comment]
closing due to a lack of response
