### ISSUE TITLE
It doesn't fallback on the next image

### ISSUE THREAD

**Issue by AndreiDudeOne** [mbrevda/react-image#267]
Hi,

There are certain situations where the src URL gives a 404. In that circumstance the component doesn't fallback to the next image, and on the next image and so on. It just displays the broken image icon.
Am I missing something? 

I know this can be solved with some Ajax checking on the front-end and feeding the right URL, but I want to make sure this isn't taken care of natively (which It should imop)

Thanks!

**Comment by mbrevda** [comment]
as per https://github.com/mbrevda/react-image/issues/254, if they browser think it received an image the fallback won't be displayed. A future version of this lib will allow that to be overwritten with a custom implementation 🤞 .
