### ISSUE TITLE
[BUG ^3.0.0] Refreshing page causes images to fail to load

### ISSUE THREAD

**Issue by AJHenry** [mbrevda/react-image#275]
Upgrading from `2.4.0` to `^3.0.0` breaks reloading the page with images on it.

[Sandbox link](https://codesandbox.io/s/vibrant-bhabha-u4s0q) 

Reproduction steps: 
- Load the page and you'll see the bananas (sometimes you won't even see the 🍌on initial load)
- Refresh the sandbox window you'll see the bananas no longer display

This behavior works on `^2.4.0` however

**Comment by mbrevda** [comment]
I've temporarily rolled back to 2.4.0 until we can get #273 resolved. Will revisit after that

**Comment by mbrevda** [comment]
React image expects a string which it will try to load from the network. If the image is already included in your js bundle, why not load it directly?

**Comment by AJHenry** [comment]
We have a bunch of react projects rendered server/client side so trying to get images to pull from a URL isn't feasible for us without a rework

Plus the [create react docs](https://create-react-app.dev/docs/adding-images-fonts-and-files/) _specifically_ call out this pattern

**Comment by mbrevda** [comment]
Got it, good catch! Thanks so much for reporting! Hope to cut a new release later today with a fix

**Comment by mbrevda** [comment]
You can test with the latest canary, should be fixed
