### ISSUE TITLE
Module not found: Can't resolve 'react-image/useImage'

### ISSUE THREAD

**Issue by jpainam** [mbrevda/react-image#283]
After running `npm i react-image` or `npm install --save react-image`, I still get this error.
any idea what is going wrong

**Comment by jpainam** [comment]
But using this `import  { useImage }  from 'react-image';`, and 
```javascript
const { src, isLoading, error } = useImage({
        srcList: product.featuredImage
    })
```
I get this error
`TypeError: Cannot destructure property 'src' of 'react_image__WEBPACK_IMPORTED_MODULE_14___default(...)(...)' as it is null.`

**Comment by mbrevda** [comment]
There is currently an issue consuming react-image as a module. See https://github.com/mbrevda/react-image/issues/273
