### ISSUE TITLE
[3.0.3] TS definition for <Img> conflicts with documentation

### ISSUE THREAD

**Issue by mxcl** [mbrevda/react-image#284]
> Type '{ src: string; height: number; alt: string; }' is missing the following properties from type 'Pick<useImageProps, "imgPromise" | "useSuspense">': imgPromise, useSuspense

```ts
return <Img src={src} height={height} alt={alt} />
```

Either docs are incorrect or the definition is incorrectly making these properties required rather than optional.

**Comment by mbrevda** [comment]
I've temporarily rolled back to 2.4.0 until we can get #273 resolved. Will revisit after that

**Comment by mbrevda** [comment]
Should be fixed by https://github.com/mbrevda/react-image/commit/bc3ab8189f88f14eba8d1fc3a8249eb5bb6dab81, we can reopen if it's not (these changes may not have been published yet, might want to test with canary)
