### ISSUE TITLE
How to cache downloaded images

### ISSUE THREAD

**Issue by athenawisdoms** [mbrevda/react-image#288]
Hi, before using `react-image` in my Electron + React + Redux app, my render function looked like

```
    render() {
        return (
            <div className="col-xs-1">
                <div className="img-container">
                    <img src={ this.props.item.imageUrl } width="100%" />
                </div> 
            </div> 
        )
```

and when a user switched to another route and back to the initial route containing the component, the image are loaded from cache, or at least not downloaded again.

However, after converting it to use `react-image` v4.0.0, after the user switches route and back again, all the previously downloaded images are downloaded once more. This can be confirmed by looking at the Network tab of Electron's Chrome DevTools.

```
const LazyImage = (props) => {
    const { src } = useImage({
        srcList: props.src
    });

    return <img src={src} />
}


...


class MyItem extends PureComponent {

    ...

    render() {
        return (
            <div className="col-xs-1">
                <div className="img-container">
                    <Suspense fallback={<Skeleton height={200} />}>
                        <LazyImage src={ this.props.item.imageUrl } />
                    </Suspense>
                </div> 
            </div> 
        )
    }
}
```

Is it possible to allow `react-image` to save/load the initial image download from cache? Thanks!

**Comment by kezzay** [comment]
Might be worth checking if you have the 'disable cache' option selected in chrome dev tool. This option is normally selected by default when the tool is open, leading to multiple network requests.

https://github.com/mbrevda/react-image/issues/328#issuecomment-656940859
