### ISSUE TITLE
lib v4.x.x have broken for loader

### ISSUE THREAD

**Issue by JudeNiroshan** [mbrevda/react-image#309]
I was using v3.0.3 version has recently updated my dependency. It caused breaking my entire app because of compile error coming from the library.

```
<Img
              src={promotionBanner}
              loader={<MyLoader/>}
            />
```

**Comment by mbrevda** [comment]
Can you elaborate on the issue?

**Comment by JudeNiroshan** [comment]
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`

Above error I'm getting on my app when I swtich to v4.0.1 of react-image.
This is how I use react-image
```

import Img from "react-image"

<section className="homepage-banner">
        <Carousel
          transitionTime={250}
          infiniteLoop
          autoPlay={true}
          showThumbs={false}
          showArrows={true}
          stopOnHover={false}
          >
          <div className="homepage-banner-image-container">
            <Img
              src={promotionBanner}
              loader={<MyLoader/>}
            />
          </div>
          <div className="homepage-banner-image-container">
            <Img
              src={testBanner}
              loader={<MyLoader/>}
            />
          </div>
        </Carousel>
</section>
```

It says the compile error happened to start on creating this particular div element

```
<div className="homepage-banner-image-container">
            <Img
              src={promotionBanner}
              loader={<MyLoader/>}
            />
</div>
```

**Comment by mbrevda** [comment]
Please see the Upgrading guide for how to deal with the braking changes in 4.x: https://github.com/mbrevda/react-image/blob/master/UPGRADE.md

**Comment by JudeNiroshan** [comment]
Thank you. It was the import change I had to do.

`import {Img} from 'react-image'`
