### ISSUE TITLE
Crash within useImage: The above error occurred in the <MyImageComponent> component

### ISSUE THREAD

**Issue by jordymeow** [mbrevda/react-image#326]
Hi,

I am using the last version of react-image (4.0.2) and react (16.13.1).  I am getting this error and there is nothing _above_ it:

```
react-dom.development.js:19527 The above error occurred in the <MyImageComponent> component:
    in MyImageComponent (at ...)

[...]

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

This error only happens with the hook. 

```
import { Img, useImage } from 'react-image'

const MyImageComponent = () => {
  // I can do a console.log here...
  const {src} = useImage({ srcList: imgUrl })
  // But the code never runs after useImage
  return <img src={src} />
};	
```

Otherwise, this works:

```
import { Img, useImage } from 'react-image'

const MyImageComponent = () => <Img src={imgUrl} />;
```

Have you seen this issue before? Thank you :)

**Comment by mbrevda** [comment]
No, I haven't. Are you using an error boundary? Can you provide a codesandbox?

**Comment by jordymeow** [comment]
I am afraid it might be linked to something else, and I suspect that a simple codesandbox will work (otherwise you would have ran into the issue as well). 

I am using NextJS, maybe it's related? And I don't know anything about Error Boundary, but it seems like NextJS might be using it. I will try to look a bit more into this, in order to get a proper error... if you have any idea that could help me, I am interested.

**Comment by mbrevda** [comment]
Got it. I'll close the issue for now, we can reopen if there is something further we can do

**Comment by jordymeow** [comment]
Indeed, { useSuspense: false } needs to be explicitely set to false if <Suspense> is actually not used, otherwise it crashes without specific error.

**Comment by fogmoon** [comment]
I Meet same issue when the image url get 404 response.

In dev mode, tons of `React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.`  messages freeze the Chrome browser.

The **above error** occurred in the < MyImageComponent > component:

```
Uncaught Event {isTrusted: true, type: "error", target: null, currentTarget: null, eventPhase: 0, …}
```

Also use NextJS, the code part just simple like @jordymeow.
