### ISSUE TITLE
Noticeable delay between suspense fallback and image

### ISSUE THREAD

**Issue by nathanburgess** [mbrevda/react-image#328]
I'm using the example from the readme to use `Suspense` to display a spinner while I await the image to be loaded. However, once the image is loaded, the spinner is removed and there's a noticeable delay before the image pops in. Is there some way to keep the loader visible until the image is completely rendered?

**Comment by mbrevda** [comment]
I'm not sure. Could we see a codesandbox of the issue?

**Comment by kezzay** [comment]
@nathanburgess Worth checking if you're encountering this issue due to having chrome dev tools open. Normally when you have the tool open, caching is disabled as default. This may lead chrome to download the image again when your component finally renders it after react-image caches it.

**Comment by kezzay** [comment]
<img width="289" alt="cache-chrome" src="https://user-images.githubusercontent.com/68132513/87211213-561f3400-c310-11ea-8e5a-149e92fe0a2b.png">

You can allow cache when using chrome dev tools through settings

**Comment by nathanburgess** [comment]
> @nathanburgess Worth checking if you're encountering this issue due to having chrome dev tools open. Normally when you have the tool open, caching is disabled as default. This may lead chrome to download the image again when your component finally renders it after react-image caches it.

Cache appears to have been the problem, I didn't even think about that, thanks.
