### ISSUE TITLE
With useImage, isLoading is not triggered automatically

### ISSUE THREAD

**Issue by jordymeow** [mbrevda/react-image#352]
Hi,

I am using the hook this way:

`const { src, isLoading }  = useImage({ srcList: imgUrl, useSuspense: false });`

Thing is, it keeps on loading... as long as I don't interact with the browser. Even the image is actually physically loaded properly (through the network), useImage doesn't trigger.

Is this an actual issue of react-image, or is there something to do about this?

**Comment by mbrevda** [comment]
not sure I follow, can you link to a codesandbox describing the issue?

**Comment by jordymeow** [comment]
Of course! Do you have a test sandbox already with some code for react-image? So that I can quickly clone and modify it to showcase the issue.

**Comment by mbrevda** [comment]
Unfortunately, I do not

**Comment by jordymeow** [comment]
I am really having so many issues. I tried with Suspense, and it crashes all the time (for no apparent reason - I tried to get the error with ErrorBoundary but couldn't, I have never experienced such an _undefined_ crash). I tried without Suspense, and even though it doesn't crash, useImage doesn't trigger a redraw until there is some human activity in the browser (for example, if I open the Console, move the browser, etc). 

For your information, in my case, the srcList is dynamic. I change its value from time to time (on user's action). It's maybe that your component is not handling this. I am really not sure.

It would be really awesome if you had some demo online, using codesandbox. I would love to help but I would really need a working example I could play with, and that would be useful for other users as well, I am sure.

**Comment by jordymeow** [comment]
To fix my issues, I created my own: https://gist.github.com/jordymeow/ed083811e407e89b49c0eecd7f722695. It does more or less the same as yours (with less features), the code is very short, and it works out of the box for me. Maybe that will help users running into the same issues.

**Comment by mbrevda** [comment]
Seems this is resolved?

**Comment by jordymeow** [comment]
It's more or less resolved I guess, since I am using my own useImage now :) But that also means there is an issue somewhere in your library. Cheers.

**Comment by michaelmika** [comment]
I had exactly the same problem (which seems to be very obvious: `useImage` hook is not triggered/effected when `srcList` changes and therefore does not update `isLoading` return variable). 
Thanks @jordymeow, I now switched from react-image to your simple approach and it works like a charm.

**Comment by jordymeow** [comment]
You are welcome @michaelmika, I am super happy that this lighter and simpler solution works for you too :)
