### ISSUE TITLE
I want to know, how to use imgPromise

### ISSUE THREAD

**Issue by cesarlarsson** [mbrevda/react-image#423]
Trying to use the library on my react project with typescript, so I see in the documentation that we have to use a Promise , but also requires to define srcList element. On the promise fetching an image typescript throw me always this message:

Property 'then' is missing in type 'Response' but required in type 'PromiseLike<void>'. 

Do you have a documentation about the use of it ?

**Comment by mbrevda** [comment]
This sounds like a typescript question. Feel free to reopen with project-specific information
