### ISSUE TITLE
EncodingError: Invalid image type.

### ISSUE THREAD

**Issue by acomito** [mbrevda/react-image#477]
I put this package in my project and it's worked great for me.

I tested on desktop, ipad chrome, ipad safari and had no problems.

However, I found two other users on ipad who did have this error "EncodingError: Invalid image type."

Oddly, we're all on iPadOS 14.2 but sentry has the error happening on Mobile Safari 12.0 and 12.1.2

Sounds maybe similar to these

- https://github.com/vuetifyjs/vuetify/issues/4969
- https://github.com/necolas/react-native-web/issues/1087

**Comment by mbrevda** [comment]
Sounds like a dup of https://github.com/mbrevda/react-image/issues/191#issue-310467067. Does that work for you?
