### ISSUE TITLE
Can't use ref on Img component.

### ISSUE THREAD

**Issue by tomasbal** [mbrevda/react-image#502]
Hello I have problem when trying to use "useRef" and use that ref to <Img/> then I can't reference that image using the ref.
It's throwing this error: 
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Kind regards,
Tomislav.

**Comment by mbrevda** [comment]
Please post a codesandbox demo
