### ISSUE TITLE
Loading image with JWT token

### ISSUE THREAD

**Issue by digitalw** [mbrevda/react-image#589]
Hi,
I need to add a authorization token to the request. I therefore have a method
```javascript

export default function getAuthImag(url) {
    fetch(`${url}`,
        {
            responseType: 'arraybuffer',
            headers: {
                authorization: "JWT " + localStorage.getItem('token'),
                'X-CSRF-Token': Cookies.get('csrftoken')
            }
        })
        .then(response => response.blob())
        .then(function (blob) {
            return URL.createObjectURL(blob);
        });
}

```

and I the use it in this way:

```javascript
function ProfileImage(props) {
    const user = props.user;
    const { src } = useImage({ srcList: [getAuthImag(config.get('mediaUrl') + (user.avatar != null ? user.avatar.id : "")), UserIcon] });
    return <img className="avatar" src={src} />;
}
```

However I get the error: 

```
TypeError: Object(...) is not a function
ProfileImage
D:/Ben/GitHub-Repos/dojo-manager-frontend/src/pages/profile.js:88

  85 | }
  86 | 
  87 | 
> 88 | function ProfileImage(props) {
  89 |     const user = props.user;
  90 |     console.log(user);
  91 |     const { src } = useImage({ srcList: [getAuthImag(config.get('mediaUrl') + (user.avatar != null ? user.avatar.id : "")), UserIcon] });
```

Anyx hints on how to get this to work, or even a better approach?

Thanks

**Comment by mbrevda** [comment]
I don't think returning a blob will work. At the end of the day, react-image expects to insert the image on its own, as an `<img>`

**Comment by digitalw** [comment]
Hi thanks. Would using imgPromise be a possibility? if yes, could you (anyone) give an example on how this works?
Thanks a lot.

**Comment by mbrevda** [comment]
Actually, your right - should be able to do something by replacing `imgPromise`. The challenge is that `useImage` returns the same `src` that it receives, however, in your case the `src` is not the same. I see two options here:


1. Modify your backend to allow sending the JWT via query params. This would be the simplest as it wouldn't require any modification to the default `useImage` usage
2. Create your own `imgPromise`. You'd probably want to design it so that when an image is saved the blob but resolved the original key (`src`). You'd then need to lookup the blob before using it. Here is some untested code:

```ts
// your downloaded images will be stored as data strings here
const imageCache = {};

// override the default imgPromise from https://github.com/mbrevda/react-image/blob/master/src/imagePromiseFactory.ts
const imgPromise = (src): Promise<void> => {
  return new Promise((resolve, reject) => {
    fetch(`${url}`, {
      responseType: "arraybuffer",
      headers: {
        authorization: "JWT " + localStorage.getItem("token"),
        "X-CSRF-Token": Cookies.get("csrftoken"),
      },
    })
      .then((response) => response.blob())
      .then(function (blob) {
        imageCache[src] = URL.createObjectURL(blob);
        return resolve(src);
      })
      .catch(reject);
  });
};

function ProfileImage(props) {
  const user = props.user;
  const userAvatarSrc = getAuthImag(
    config.get("mediaUrl") + (user.avatar != null ? user.avatar.id : "")
  );

  // src will be the original src, not the actual base64 image.
  const { src } = useImage({ srcList: [userAvatarSrc, UserIcon], imgPromise });

  // lookup the base64 image based on the src string in the imageCache object
  return <img className="avatar" src={imageCache[src]} />;
}

```

**Comment by digitalw** [comment]
Hi Thanks.
I was not able to get your solution to work. However, I might give it another go later on. Looks promising.  For now i made a hardcoded fix but will revisit if i need a more generic approach. 

Thanks.

**Comment by braco** [comment]
@mbrevda is that still the technique you'd recommend for injecting headers into an image request? Getting images with something like an auth header is a huge pain point right now.

**Comment by mbrevda** [comment]
The idea is that you can easily replace the image fetcher with any implementation that works for you and reuse that across your project. So basically you can create your own hook by supplying your custom logic without having to reimplement the loading/fallback/suspense parts. So yes: still recommended!
