### ISSUE TITLE
decode doesn't seem to work with baseline-encoded images

### ISSUE THREAD

**Issue by DanielRuf** [mbrevda/react-image#743]
![grafik](https://user-images.githubusercontent.com/827205/138849863-51d24f33-d529-4e24-bb64-0824c6ccc54c.png)

Tested in Chrome with big baseline-encoded images that are loaded from a relative local path.

https://caniuse.com/mdn-api_htmlimageelement_decode

**Comment by mbrevda** [comment]
We can't really tell the difference between image types - only wait for the browser to fire `onload`/`decode`. If `decode` doesn't work for your use case, I'd recommend [disabling it](https://github.com/mbrevda/react-image#decode-before-paint)
