### ISSUE TITLE
Failed to parse source map index.js.map after upgrading to CRA 5/Webpack 5

### ISSUE THREAD

**Issue by RabeeAbuBaker** [mbrevda/react-image#852]
The project was recently upgraded from using Craco to CRA5, the same warning showed up for dozens of libraries but upgrading them to the latest versions fixed the issue. We're left with the only warning coming from react-image.

See the error below: 

![Screen Shot 2022-03-14 at 2 07 30 PM](https://user-images.githubusercontent.com/38038348/158169406-bb8b5820-ee00-4166-a713-f9dd088d2799.png)

Node version: v16.14.0
NPM version: 8.5.3
react-scripts: ^5.0.0
react-image: ^4.0.3

**Comment by mbrevda** [comment]
It doesn't seem like there is a sourcemap included for any of the builds. Need to see how to remove that line

**Comment by realstrategos** [comment]
also seeing this

**Comment by mbrevda** [comment]
Would it be preferable to include the sourcemap or to implement #890?

**Comment by realstrategos** [comment]
remove it?

**Comment by mbrevda** [comment]
cc @deskoh

**Comment by deskoh** [comment]
> cc @deskoh

Since it's not a complicated library suggest to remove it? Any consideration or strong use case to include source map for 3rd party libs?

**Comment by mbrevda** [comment]
My argument would make that it provides more context to errors allowing users to either determine how they missuses the component leading to the error or helping the user pinpoint the point of error leading to better bug reports.

Guess I'll take cues from some other libs and see what makes sense. Thanks all!

**Comment by ericklind** [comment]
I'm running into this as well and really need it to be fixed. Otherwise the only way to get my project to run is to turn off all sourcemaps, which is not ideal.

**Comment by monstik** [comment]
Hello, the following solution helped me:

1) Delete the node_modules folder and the package-lock.json or yarn.lock file.
2) Run the command npm install or yarn to reinstall the dependencies.
After that, the error disappeared.
