### ISSUE TITLE
Manually reloading the image when it fails to load

### ISSUE THREAD

**Issue by joker-777** [mbrevda/react-image#864]
Hi, I would like to give the user the option to reload the image in case it failed to load. Something like this

```js
  const error_renderer = ({resetErrorBoundary}) => ( 
    <LoadingErrorFallback onClick={resetErrorBoundary}/>
  ) 
  return ( 
    <ErrorBoundary fallbackRender={error_renderer}>
      <Suspense fallback={<div className="spinner"></div>}>
        <Image image_url={image_url} />
      </Suspense>
    </ErrorBoundary>
  ) 
```

Unfortunately, this doesn't work because `react-image` stores the promise inside this cache object and doesn't try to load it again. What is the best solution here?

**Comment by mbrevda** [comment]
Would adding a cache buster work? I. E. Append foo="something Random" to
the url

**Comment by joker-777** [comment]
@mbrevda Thanks a lot for your reply. Yes, it would be a workaround but not the best solution.

**Comment by mbrevda** [comment]
Will keep this use case in mind, although not sure there is much to do

**Comment by mbrevda** [comment]
The alternative and more react-y would be to add a `key` prop to the `<Img />` component
