### ISSUE TITLE
App freeze when using React 18

### ISSUE THREAD

**Issue by Myrfion** [mbrevda/react-image#952]
Hello, I upgraded the app to react 18 from reacting 17 and in the places of the app where I use react-image, it gets freezer and stops responding (feels like it gets in some infinite loop). Has anybody else faced something like that?

**Comment by Myrfion** [comment]
@anthonykrivonos I was losing my mind for almost a day, cuz I wasn't able to believe that nobody faces that issue with the package that has 50k downloads weekly...

**Comment by mbrevda** [comment]
Thanks guys for reporting. I haven't moved any of my phone projects to React 18 yet, but will prioritize looking in to this.

**Comment by mbrevda** [comment]
I set up a [branch](https://github.com/mbrevda/react-image/tree/moveToEsbuild) that, among other things, moves to react 18 but am not seeing this. Did I miss something?

Can you please link to a codesandbox illustrating the issue? Alternatively, try cloning this project, run `npm run dev`, and visit http://localhost:3888/ to run the test suit.

**Comment by shardbearer-shri** [comment]
Is there any other alternate solution for this ? All i wanted to do was render a fallback element on image error :(

**Comment by mgoodfellow** [comment]
Well, I made a quick component which is drop in compatible just for fallback images when `src` is an array, and I always know it will have a length of 2 - it's hacky but we really just needed to quickly unblock ourselves and also prove that it was only react-image which was causing issues (in our case that was the case)

```
import isArray from 'lodash/isArray';
import React, { useEffect, useRef, useState } from 'react';

type ImgProps = {
    src: string | string[];
    alt?: string;
    style?: any;
    srcSet?: string;
};

const HtmlImgFallback = ({ src, ...rest }: ImgProps) => {
    const [imgSrc, setImgSrc] = useState<string>(isArray(src) ? src[0] : src);
    const imgRef = useRef<HTMLImageElement>();

    useEffect(() => {
        setImgSrc(isArray(src) ? src[0] : src);
    }, [src]);

    return (
        <img
            {...rest}
            ref={imgRef}
            src={imgSrc}
            onLoad={() => {
                if (imgRef.current?.clientWidth === 0) {
                    // Broken image
                    setImgSrc(isArray(src) ? src[1] : src);
                }
            }}
            onError={() => {
                setImgSrc(isArray(src) ? src[1] : src);
            }}
        />
    );
};

export default HtmlImgFallback;
```

This doesn't fit your use case, but I'm sure you can quickly adapt it to render out a fallback component you passed in on error.

Having swapped our usage out we haven't seen any more issues - we weren't using the advanced features of react-image, so it made sense for us to use this as a stop gap as we have been forced to upgrade to React 18.

**Comment by martdavidson** [comment]
We're seeing this as well, but only when `useSuspense: false` which we need.

**Comment by clueking1** [comment]
My app freezes when using the onClick prop and then clicking the image

**Comment by idChef** [comment]
I have created reproduction of the issue on [CodeSandbox](https://codesandbox.io/s/react-image-v18-freeze-reproduction-slp58w)

**Comment by mbrevda** [comment]
Oh wow, thanks! That is sooo strange. I'll try to dig into this a bit more, open to ideas!

**Comment by idChef** [comment]
I also can't get the `useImage` approach to work [Codesandbox reproduction](https://codesandbox.io/s/react-image-useimage-hook-rcrb34)

In my app that I'm trying to implement `react-image` in I have this error: 
![image](https://user-images.githubusercontent.com/34141636/187849823-7e1e19b3-5ed2-4c88-815a-7d9506d87b62.png)

**Comment by mbrevda** [comment]
update: not 100% clear about what changed in React 18, but seems [returning earlier in the hook ](https://github.com/mbrevda/react-image/pull/966/files#diff-e032d7e8431c312be0238383c849faa0b23f0b6f86d1e2f0abf1c81fa136e53fR55) resolves the issue. Please note, PR still requires lots of work, so the fix is not ready yet.

**Comment by RykerMunn** [comment]
@mbrevda do you have an estimated timeline for when this fix might be ready? My team has had to come up with a workaround for this problem for one of the key features in our software, which is working now but we are experiencing the same freezing problem as detailed above. 

Specifically in our case we change the `src` passed to the `Img` component based on the props passed into our viewer. We make an API request to get a different sized image based on what the user's image preference is. When they change the size, we generate a new source URL and update the `Img` component. 

[This CodeSandbox](https://codesandbox.io/s/intelligent-blackwell-wdgufk?file=/src/App.js) shows approximately what our setup is. Although it doesn't appear to actually freeze in this particular case.

**Comment by 10thfloor** [comment]
We're experiencing this as well after upgrading. Has this been fixed?

**Comment by mbrevda** [comment]
Hi all - 

First of all, apologies for the delay in addressing this.

Second, I've published a canary build addressing the issue. I'd appreciate if you could take a moment to confirm that this build fixes the issue for you before I publish. You can install it with `npm i react-image@0.0.0-3e088c3494d991cfef11d13df06c9de990445785` and re-trying whatever was causing the freeze.

You can also see this working in an updated [codesandbox](https://codesandbox.io/s/react-image-v18-freeze-reproduction-forked-r1erk0?file=/src/App.js)

**Comment by mbrevda** [comment]
Was anyone able to test? Would like to release this...

**Comment by RykerMunn** [comment]
@mbrevda sorry for the delay in getting back to you. My team has deployed version 4.1.0 to our dev environment and it has solved this app freezing in our use case. 

Thank you for publishing a fix!
