### ISSUE TITLE
Is supported the srcSet attribute for responsive images  -  with downgrade.. 

### ISSUE THREAD

**Issue by mikethejet** [mbrevda/react-image#969]
Supporting the src set attribute the fallback for images? 
How to use it? 

 <Img
    src={['https://www.example.com/foo.jpg', 'https://www.example.com/bar.jpg']}
  />

 <Img
    srcset= ?? 
  />

**Comment by mbrevda** [comment]
No, srcSet is not supported. Not sure it makes sense for a library like this
