### ISSUE TITLE
How to resolve Contentful Paint element issue ? 

### ISSUE THREAD

**Issue by singhaman04** [mbrevda/react-image#976]
<Img
                    className="img-responsive2"
                    src={item.mobileImage.url}
                    fallback={"http://localhost:3000/globals/images/pdp-door.png"}
                    alt={item.image.altText}
                    sources={[
                      {
                        source: item.mobileImage.url,
                        media: "(min-width: 320px)",
                      },
                      {
                        source: item.image.url,
                        media: "(min-width: 768px)",
                      },
                    ]}
                  />

**Comment by mbrevda** [comment]
What is the issue?

**Comment by singhaman04** [comment]
This is a performance issue, mentioned in the Lighthouse report of google chrome.

**Comment by mbrevda** [comment]
Can you describe the issue?

**Comment by singhaman04** [comment]
I am trying to improve the overall performance of my application. We have used react-image in our home page.
If you run the Lighthouse report in Google Chrome, you will get the score for Performance, Accessibility, SEO etc for your application. 
Under Performance there is this issue:


**Largest Contentful Paint**
https://web.dev/lighthouse-largest-contentful-paint/?utm_source=lighthouse&utm_medium=devtools (refer this)

All, I want to know is, do we have any work around for the same using react-image.

**Comment by mbrevda** [comment]
> do we have any work around for the same using react-image.

Still unclear how any of this pertains to react-image so really unsure. Perhaps a minimal reproduction would help?
