### ISSUE TITLE
Could not resolve "@babel/runtime/helpers/defineProperty"

### ISSUE THREAD

**Issue by saurabhmehta1601** [mbrevda/react-image#977]
While trying to use `Img` component from react-image I am facing this error . Here is a screenshot 
![Screenshot (13)](https://user-images.githubusercontent.com/57309205/216441364-33a77e71-6b19-4584-9872-cb01162626c8.png)

**Comment by mbrevda** [comment]
looks like `@babel/runtime` is needed. A future release should eliminate that need.
